spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JJS857012499/Security-Config
server:
  port: 8750

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



