spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JJS857012499/Security-Config
server:
  port: 8750

eureka:
  client:
    service-url:
      defaultZone: http://120.25.201.80:8761/eureka,http://120.25.201.80:8762/eureka



