logging:
    level:
        tk.mybatis: DEBUG
        com.zd.admin: DEBUG
spring:
    application:
        name: admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://120.25.201.80:3306/ag_admin?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.zd.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 8763

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://120.25.201.80:8761/eureka/,http://120.25.201.80:8762/eureka/
swagger:
    basepackage: com.zd.admin
    service:
        name: admin
        description: admin 后端服务
        developer:


