spring:
  application:
    name: center
---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: @eureka.server.port01@
eureka:
  instance:
    hostname: @eureka.server.name01@                               # 指定当profile=peer1时，主机名
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: @eureka.client.serviceUrl.defaultZone.02@   # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: peer2
server:
  port: @eureka.server.port02@
eureka:
  instance:
    hostname: @eureka.server.name02@
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: @eureka.client.serviceUrl.defaultZone.01@